-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employees
(
    id integer NOT NULL,
    fio character varying(60) COLLATE pg_catalog."default" NOT NULL,
    post character varying(30) COLLATE pg_catalog."default",
    experience real,
    profile_id integer,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.films
(
    id integer NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    year integer,
    country character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT films_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.visitors
(
    id integer NOT NULL,
    fio character varying(60) COLLATE pg_catalog."default" NOT NULL,
    age integer NOT NULL,
    profile_id integer,
    CONSTRAINT visitors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.seanses
(
    id integer NOT NULL,
    date date NOT NULL,
    price real NOT NULL,
    duration integer,
    film_id integer,
    hall_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.seanses_employees
(
    seanses_id serial NOT NULL,
    employees_id serial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seanses_visitors
(
    seanses_id serial NOT NULL,
    visitors_id serial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.halls
(
    id integer NOT NULL,
    type character varying(10) NOT NULL,
    seats_count integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profiles
(
    id integer NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL,
    role character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (profile_id)
    REFERENCES public.profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.visitors
    ADD FOREIGN KEY (profile_id)
    REFERENCES public.profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses
    ADD FOREIGN KEY (firm_id)
    REFERENCES public.films (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses
    ADD FOREIGN KEY (hall_id)
    REFERENCES public.halls (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses
    ADD FOREIGN KEY (film_id)
    REFERENCES public.films (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses_employees
    ADD FOREIGN KEY (seanses_id)
    REFERENCES public.seanses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses_employees
    ADD FOREIGN KEY (employees_id)
    REFERENCES public.employees (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses_visitors
    ADD FOREIGN KEY (seanses_id)
    REFERENCES public.seanses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seanses_visitors
    ADD FOREIGN KEY (visitors_id)
    REFERENCES public.visitors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;